//%GenSrc:1:BBqcSehsi0SL7khHmTYa1w
//%CodeKey:gzNRlQNDZkatsinZIiRlDA
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Customer.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    [RequireComponent(typeof(Cart))]
    public partial class Customer : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            int n0c = -1;
            int n14c = -1;
            int n15c = -1;
            int n16c = -1;
            int n17c = -1;
            int n18c = -1;
            int n19c = -1;
            int n1c = -1;
            int n2c = -1;
            int n3c = -1;
            int n4c = -1;
            int n5c = -1;
            int n6c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n15_1r = NodeVal.Invalid;
            NodeVal n16_1r = NodeVal.Invalid;
            NodeVal n17_1r = NodeVal.Invalid;
            NodeVal n18_1r = NodeVal.Invalid;
            NodeVal n19_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n4_1r = NodeVal.Invalid;
            NodeVal n5_1r = NodeVal.Invalid;
            NodeVal n6_1r = NodeVal.Invalid;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 43:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 6) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(39, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 7;
                        node = 7;
                        n1_1r = NodeVal.Success;
                        break;
                    case 44:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 9) {
                            node = ++n1c;
                        } else {
                            n1c = 7;
                            node = 43;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(39, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 10;
                        node = 10;
                        n2_1r = NodeVal.Success;
                        break;
                    case 45:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 11) {
                            node = ++n2c;
                        } else {
                            n2c = 10;
                            node = 43;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 12;
                        node = 12;
                        n3_1r = NodeVal.Success;
                        break;
                    case 46:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 14) {
                            node = ++n3c;
                        } else {
                            n3c = 12;
                            node = 43;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 37;
                        node = 37;
                        n4_1r = NodeVal.Success;
                        break;
                    case 47:

                        n4_1r = (NodeVal)System.Math.Max((int)n4_1r, (int)ret);
                        if (ret == NodeVal.Success && n4c < 38) {
                            node = ++n4c;
                        } else {
                            n4c = 37;
                            node = 43;
                            ret = n4_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 5:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n5c = 39;
                        node = 39;
                        n5_1r = NodeVal.Success;
                        break;
                    case 48:

                        n5_1r = (NodeVal)System.Math.Max((int)n5_1r, (int)ret);
                        if (ret == NodeVal.Success && n5c < 40) {
                            node = ++n5c;
                        } else {
                            n5c = 39;
                            node = 43;
                            ret = n5_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 6:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n6c = 41;
                        node = 41;
                        n6_1r = NodeVal.Success;
                        break;
                    case 49:

                        n6_1r = (NodeVal)System.Math.Max((int)n6_1r, (int)ret);
                        if (ret == NodeVal.Success && n6c < 42) {
                            node = ++n6c;
                        } else {
                            n6c = 41;
                            node = 43;
                            ret = n6_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 7:

                        ret = (!this.spawned)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, ret, false, false);
                        #endif
                        node = 44;
                        break;
                    case 8:


                        do
                        {
                            ret = (this.StartShopping());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 44;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 9:


                        do
                        {
                            ret = (this.MoveTowards());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 44;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 10:

                        ret = ((transform.position - (this.targetLocation).position).sqrMagnitude >= (9f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(41, _liveHandle, ret, false, false);
                        #endif
                        node = 45;
                        break;
                    case 11:


                        do
                        {
                            ret = (this.MoveTowards());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(42, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 45;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(42, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 12:

                        ret = (this.spawned)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, ret, false, false);
                        #endif
                        node = 46;
                        break;
                    case 13:

                        ret = (!this.shoppingDone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, ret, false, false);
                        #endif
                        node = 46;
                        break;
                    case 14:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n14c = 15;
                        node = 15;
                        break;
                    case 57:

                        if(ret != NodeVal.Success) {
                            if (++n14c > 19) {
                                n14c = 15;
                                node = 46;
                            } else {
                                node = n14c;
                            }
                        } else {
                            n14c = 15;
                            node = 46;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 15:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n15c = 20;
                        node = 20;
                        n15_1r = NodeVal.Success;
                        break;
                    case 58:

                        n15_1r = (NodeVal)System.Math.Max((int)n15_1r, (int)ret);
                        if (ret == NodeVal.Success && n15c < 23) {
                            node = ++n15c;
                        } else {
                            n15c = 20;
                            node = 57;
                            ret = n15_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 16:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n16c = 24;
                        node = 24;
                        n16_1r = NodeVal.Success;
                        break;
                    case 59:

                        n16_1r = (NodeVal)System.Math.Max((int)n16_1r, (int)ret);
                        if (ret == NodeVal.Success && n16c < 26) {
                            node = ++n16c;
                        } else {
                            n16c = 24;
                            node = 57;
                            ret = n16_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 17:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n17c = 27;
                        node = 27;
                        n17_1r = NodeVal.Success;
                        break;
                    case 60:

                        n17_1r = (NodeVal)System.Math.Max((int)n17_1r, (int)ret);
                        if (ret == NodeVal.Success && n17c < 30) {
                            node = ++n17c;
                        } else {
                            n17c = 27;
                            node = 57;
                            ret = n17_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 18:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n18c = 31;
                        node = 31;
                        n18_1r = NodeVal.Success;
                        break;
                    case 61:

                        n18_1r = (NodeVal)System.Math.Max((int)n18_1r, (int)ret);
                        if (ret == NodeVal.Success && n18c < 33) {
                            node = ++n18c;
                        } else {
                            n18c = 31;
                            node = 57;
                            ret = n18_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 19:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n19c = 34;
                        node = 34;
                        n19_1r = NodeVal.Success;
                        break;
                    case 62:

                        n19_1r = (NodeVal)System.Math.Max((int)n19_1r, (int)ret);
                        if (ret == NodeVal.Success && n19c < 36) {
                            node = ++n19c;
                        } else {
                            n19c = 34;
                            node = 57;
                            ret = n19_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 20:

                        ret = (!this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif
                        node = 58;
                        break;
                    case 21:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif
                        node = 58;
                        break;
                    case 22:

                        ret = (this.doneWithCurrentAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif
                        node = 58;
                        break;
                    case 23:


                        do
                        {
                            ret = (this.MoveToNextAisleStart());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 58;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 24:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif
                        node = 59;
                        break;
                    case 25:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif
                        node = 59;
                        break;
                    case 26:

                        ret = (this.doneWithCurrentAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif
                        node = 59;
                        break;
                    case 27:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, false, false);
                        #endif
                        node = 60;
                        break;
                    case 28:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, ret, false, false);
                        #endif
                        node = 60;
                        break;
                    case 29:

                        ret = (!this.doneWithCurrentAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif
                        node = 60;
                        break;
                    case 30:


                        do
                        {
                            ret = (this.CheckItemsOnNearAisles());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 60;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 31:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, ret, false, false);
                        #endif
                        node = 61;
                        break;
                    case 32:

                        ret = (!this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, ret, false, false);
                        #endif
                        node = 61;
                        break;
                    case 33:

                        ret = ((transform.position - (this.targetLocation).position).sqrMagnitude >= (9f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(43, _liveHandle, ret, false, false);
                        #endif
                        node = 61;
                        break;
                    case 34:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, ret, false, false);
                        #endif
                        node = 62;
                        break;
                    case 35:

                        ret = (!this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(19, _liveHandle, ret, false, false);
                        #endif
                        node = 62;
                        break;
                    case 36:


                        do
                        {
                            ret = (this.getItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 62;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 37:

                        ret = (!this.checkingOut)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, ret, false, false);
                        #endif
                        node = 47;
                        break;
                    case 38:


                        do
                        {
                            ret = (this.MoveToEnd());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 47;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 39:

                        ret = (!this.gone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, ret, false, false);
                        #endif
                        node = 48;
                        break;
                    case 40:


                        do
                        {
                            ret = (this.checkout());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 48;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 41:


                        do
                        {
                            ret = (this.MoveToExit());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 49;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 42:


                        do
                        {
                            ret = (this.Leave());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 49;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "BBqcSehsi0SL7khHmTYa1w") {
                _live = live;
                codeMatch = (codeKey == "gzNRlQNDZkatsinZIiRlDA");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
