//%GenSrc:1:BBqcSehsi0SL7khHmTYa1w
//%CodeKey:DI/6uu9PbESR490ohJo4dg
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Customer.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    [RequireComponent(typeof(Cart))]
    public partial class Customer : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            int n0c = -1;
            int n15c = -1;
            int n16c = -1;
            int n17c = -1;
            int n18c = -1;
            int n19c = -1;
            int n1c = -1;
            int n20c = -1;
            int n2c = -1;
            int n3c = -1;
            int n4c = -1;
            int n5c = -1;
            int n6c = -1;
            int n7c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n16_1r = NodeVal.Invalid;
            NodeVal n17_1r = NodeVal.Invalid;
            NodeVal n18_1r = NodeVal.Invalid;
            NodeVal n19_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n20_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n4_1r = NodeVal.Invalid;
            NodeVal n5_1r = NodeVal.Invalid;
            NodeVal n6_1r = NodeVal.Invalid;
            NodeVal n7_1r = NodeVal.Invalid;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 49:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 7) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 8;
                        node = 8;
                        n1_1r = NodeVal.Success;
                        break;
                    case 50:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 10) {
                            node = ++n1c;
                        } else {
                            n1c = 8;
                            node = 49;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(47, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 11;
                        node = 11;
                        n2_1r = NodeVal.Success;
                        break;
                    case 51:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 12) {
                            node = ++n2c;
                        } else {
                            n2c = 11;
                            node = 49;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(47, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 13;
                        node = 13;
                        n3_1r = NodeVal.Success;
                        break;
                    case 52:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 15) {
                            node = ++n3c;
                        } else {
                            n3c = 13;
                            node = 49;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 38;
                        node = 38;
                        n4_1r = NodeVal.Success;
                        break;
                    case 53:

                        n4_1r = (NodeVal)System.Math.Max((int)n4_1r, (int)ret);
                        if (ret == NodeVal.Success && n4c < 40) {
                            node = ++n4c;
                        } else {
                            n4c = 38;
                            node = 49;
                            ret = n4_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 5:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n5c = 41;
                        node = 41;
                        n5_1r = NodeVal.Success;
                        break;
                    case 54:

                        n5_1r = (NodeVal)System.Math.Max((int)n5_1r, (int)ret);
                        if (ret == NodeVal.Success && n5c < 43) {
                            node = ++n5c;
                        } else {
                            n5c = 41;
                            node = 49;
                            ret = n5_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 6:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(39, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n6c = 44;
                        node = 44;
                        n6_1r = NodeVal.Success;
                        break;
                    case 55:

                        n6_1r = (NodeVal)System.Math.Max((int)n6_1r, (int)ret);
                        if (ret == NodeVal.Success && n6c < 46) {
                            node = ++n6c;
                        } else {
                            n6c = 44;
                            node = 49;
                            ret = n6_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(39, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 7:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(41, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n7c = 47;
                        node = 47;
                        n7_1r = NodeVal.Success;
                        break;
                    case 56:

                        n7_1r = (NodeVal)System.Math.Max((int)n7_1r, (int)ret);
                        if (ret == NodeVal.Success && n7c < 48) {
                            node = ++n7c;
                        } else {
                            n7c = 47;
                            node = 49;
                            ret = n7_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(41, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 8:

                        ret = (!this.spawned)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, ret, false, false);
                        #endif
                        node = 50;
                        break;
                    case 9:


                        do
                        {
                            ret = (this.StartShopping());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 50;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 10:


                        do
                        {
                            ret = (this.MoveTowards());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 50;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 11:

                        ret = ((transform.position - (this.targetLocation).position).sqrMagnitude >= (1f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(49, _liveHandle, ret, false, false);
                        #endif
                        node = 51;
                        break;
                    case 12:


                        do
                        {
                            ret = (this.MoveTowards());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(48, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 51;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(48, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 13:

                        ret = (this.spawned)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, ret, false, false);
                        #endif
                        node = 52;
                        break;
                    case 14:

                        ret = (!this.shoppingDone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, ret, false, false);
                        #endif
                        node = 52;
                        break;
                    case 15:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n15c = 16;
                        node = 16;
                        break;
                    case 64:

                        if(ret != NodeVal.Success) {
                            if (++n15c > 20) {
                                n15c = 16;
                                node = 52;
                            } else {
                                node = n15c;
                            }
                        } else {
                            n15c = 16;
                            node = 52;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 16:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n16c = 21;
                        node = 21;
                        n16_1r = NodeVal.Success;
                        break;
                    case 65:

                        n16_1r = (NodeVal)System.Math.Max((int)n16_1r, (int)ret);
                        if (ret == NodeVal.Success && n16c < 24) {
                            node = ++n16c;
                        } else {
                            n16c = 21;
                            node = 64;
                            ret = n16_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 17:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n17c = 25;
                        node = 25;
                        n17_1r = NodeVal.Success;
                        break;
                    case 66:

                        n17_1r = (NodeVal)System.Math.Max((int)n17_1r, (int)ret);
                        if (ret == NodeVal.Success && n17c < 27) {
                            node = ++n17c;
                        } else {
                            n17c = 25;
                            node = 64;
                            ret = n17_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 18:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n18c = 28;
                        node = 28;
                        n18_1r = NodeVal.Success;
                        break;
                    case 67:

                        n18_1r = (NodeVal)System.Math.Max((int)n18_1r, (int)ret);
                        if (ret == NodeVal.Success && n18c < 31) {
                            node = ++n18c;
                        } else {
                            n18c = 28;
                            node = 64;
                            ret = n18_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 19:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n19c = 32;
                        node = 32;
                        n19_1r = NodeVal.Success;
                        break;
                    case 68:

                        n19_1r = (NodeVal)System.Math.Max((int)n19_1r, (int)ret);
                        if (ret == NodeVal.Success && n19c < 34) {
                            node = ++n19c;
                        } else {
                            n19c = 32;
                            node = 64;
                            ret = n19_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 20:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n20c = 35;
                        node = 35;
                        n20_1r = NodeVal.Success;
                        break;
                    case 69:

                        n20_1r = (NodeVal)System.Math.Max((int)n20_1r, (int)ret);
                        if (ret == NodeVal.Success && n20c < 37) {
                            node = ++n20c;
                        } else {
                            n20c = 35;
                            node = 64;
                            ret = n20_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 21:

                        ret = (!this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif
                        node = 65;
                        break;
                    case 22:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif
                        node = 65;
                        break;
                    case 23:

                        ret = (this.doneWithCurrentAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif
                        node = 65;
                        break;
                    case 24:


                        do
                        {
                            ret = (this.MoveToNextAisleStart());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 65;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 25:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif
                        node = 66;
                        break;
                    case 26:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif
                        node = 66;
                        break;
                    case 27:

                        ret = (this.doneWithCurrentAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif
                        node = 66;
                        break;
                    case 28:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, false, false);
                        #endif
                        node = 67;
                        break;
                    case 29:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, ret, false, false);
                        #endif
                        node = 67;
                        break;
                    case 30:

                        ret = (!this.doneWithCurrentAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif
                        node = 67;
                        break;
                    case 31:


                        do
                        {
                            ret = (this.CheckItemsOnNearAisles());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 67;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 32:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, ret, false, false);
                        #endif
                        node = 68;
                        break;
                    case 33:

                        ret = (!this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, ret, false, false);
                        #endif
                        node = 68;
                        break;
                    case 34:

                        ret = ((transform.position - (this.targetLocation).position).sqrMagnitude >= (9f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, ret, false, false);
                        #endif
                        node = 68;
                        break;
                    case 35:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, ret, false, false);
                        #endif
                        node = 69;
                        break;
                    case 36:

                        ret = (!this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(19, _liveHandle, ret, false, false);
                        #endif
                        node = 69;
                        break;
                    case 37:


                        do
                        {
                            ret = (this.getItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 69;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 38:

                        ret = (this.shoppingDone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(45, _liveHandle, ret, false, false);
                        #endif
                        node = 53;
                        break;
                    case 39:

                        ret = (!this.readyToCheckOut)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(46, _liveHandle, ret, false, false);
                        #endif
                        node = 53;
                        break;
                    case 40:


                        do
                        {
                            ret = (this.MoveToEnd());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(44, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 53;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(44, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 41:

                        ret = (this.readyToCheckOut)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, ret, false, false);
                        #endif
                        node = 54;
                        break;
                    case 42:

                        ret = (!this.doneCheckingOut)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, ret, false, false);
                        #endif
                        node = 54;
                        break;
                    case 43:


                        do
                        {
                            ret = (this.checkout());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 54;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 44:

                        ret = (this.doneCheckingOut)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, ret, false, false);
                        #endif
                        node = 55;
                        break;
                    case 45:

                        ret = (!this.gone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(43, _liveHandle, ret, false, false);
                        #endif
                        node = 55;
                        break;
                    case 46:


                        do
                        {
                            ret = (this.MoveToExit());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 55;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 47:

                        ret = (this.gone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(42, _liveHandle, ret, false, false);
                        #endif
                        node = 56;
                        break;
                    case 48:


                        do
                        {
                            ret = (this.Leave());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 56;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "BBqcSehsi0SL7khHmTYa1w") {
                _live = live;
                codeMatch = (codeKey == "DI/6uu9PbESR490ohJo4dg");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
