//%GenSrc:1:BBqcSehsi0SL7khHmTYa1w
//%CodeKey:jnrL8QdkXUeoDsEim0JNqA
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Customer.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    public partial class Customer : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            int n0c = -1;
            int n10c = -1;
            int n11c = -1;
            int n12c = -1;
            int n13c = -1;
            int n1c = -1;
            int n2c = -1;
            int n3c = -1;
            int n4c = -1;
            int n9c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n10_1r = NodeVal.Invalid;
            NodeVal n11_1r = NodeVal.Invalid;
            NodeVal n12_1r = NodeVal.Invalid;
            NodeVal n13_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n4_1r = NodeVal.Invalid;
            Vector3 v1 = Vector3.zero;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 32:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 4) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 5;
                        node = 5;
                        n1_1r = NodeVal.Success;
                        break;
                    case 33:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 7) {
                            node = ++n1c;
                        } else {
                            n1c = 5;
                            node = 32;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 8;
                        node = 8;
                        n2_1r = NodeVal.Success;
                        break;
                    case 34:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 9) {
                            node = ++n2c;
                        } else {
                            n2c = 8;
                            node = 32;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 28;
                        node = 28;
                        n3_1r = NodeVal.Success;
                        break;
                    case 35:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 30) {
                            node = ++n3c;
                        } else {
                            n3c = 28;
                            node = 32;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n4c = 31;
                        node = 31;
                        n4_1r = NodeVal.Success;
                        break;
                    case 36:

                        n4_1r = (NodeVal)System.Math.Max((int)n4_1r, (int)ret);
                        if (ret == NodeVal.Success && n4c < 31) {
                            node = ++n4c;
                        } else {
                            n4c = 31;
                            node = 32;
                            ret = n4_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 5:

                        ret = (!this.spawned)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif
                        node = 33;
                        break;
                    case 6:


                        do
                        {
                            ret = (this.PickFirstAisle());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 33;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 7:


                        do
                        {
                                v1 = Vector3.zero;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 3f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 33;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 8:

                        ret = (!this.shoppingDone)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif
                        node = 34;
                        break;
                    case 9:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n9c = 10;
                        node = 10;
                        break;
                    case 41:

                        if(ret != NodeVal.Success) {
                            if (++n9c > 13) {
                                n9c = 10;
                                node = 34;
                            } else {
                                node = n9c;
                            }
                        } else {
                            n9c = 10;
                            node = 34;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 10:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n10c = 14;
                        node = 14;
                        n10_1r = NodeVal.Success;
                        break;
                    case 42:

                        n10_1r = (NodeVal)System.Math.Max((int)n10_1r, (int)ret);
                        if (ret == NodeVal.Success && n10c < 17) {
                            node = ++n10c;
                        } else {
                            n10c = 14;
                            node = 41;
                            ret = n10_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 11:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n11c = 18;
                        node = 18;
                        n11_1r = NodeVal.Success;
                        break;
                    case 43:

                        n11_1r = (NodeVal)System.Math.Max((int)n11_1r, (int)ret);
                        if (ret == NodeVal.Success && n11c < 20) {
                            node = ++n11c;
                        } else {
                            n11c = 18;
                            node = 41;
                            ret = n11_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 12:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n12c = 21;
                        node = 21;
                        n12_1r = NodeVal.Success;
                        break;
                    case 44:

                        n12_1r = (NodeVal)System.Math.Max((int)n12_1r, (int)ret);
                        if (ret == NodeVal.Success && n12c < 24) {
                            node = ++n12c;
                        } else {
                            n12c = 21;
                            node = 41;
                            ret = n12_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 13:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n13c = 25;
                        node = 25;
                        n13_1r = NodeVal.Success;
                        break;
                    case 45:

                        n13_1r = (NodeVal)System.Math.Max((int)n13_1r, (int)ret);
                        if (ret == NodeVal.Success && n13c < 27) {
                            node = ++n13c;
                        } else {
                            n13c = 25;
                            node = 41;
                            ret = n13_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 14:

                        ret = (!this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif
                        node = 42;
                        break;
                    case 15:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif
                        node = 42;
                        break;
                    case 16:


                        do
                        {
                            ret = (this.PickAisle());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 42;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 17:


                        do
                        {
                                v1 = (this.targetLocation).position;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 3f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 42;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 18:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif
                        node = 43;
                        break;
                    case 19:

                        ret = (this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif
                        node = 43;
                        break;
                    case 20:


                        do
                        {
                            ret = (this.CheckItems());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 43;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 21:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, ret, false, false);
                        #endif
                        node = 44;
                        break;
                    case 22:

                        ret = (!this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, ret, false, false);
                        #endif
                        node = 44;
                        break;
                    case 23:

                        ret = ((transform.position - (this.targetLocation).position).sqrMagnitude >= (9f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(19, _liveHandle, ret, false, false);
                        #endif
                        node = 44;
                        break;
                    case 24:


                        do
                        {
                                v1 = (this.targetLocation).position;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 3f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 44;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 25:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, ret, false, false);
                        #endif
                        node = 45;
                        break;
                    case 26:

                        ret = (!this.foundItem)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, ret, false, false);
                        #endif
                        node = 45;
                        break;
                    case 27:


                        do
                        {
                            ret = (this.getItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 45;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 28:

                        ret = (!this.checkingOut)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif
                        node = 35;
                        break;
                    case 29:


                        do
                        {
                            ret = (this.checkout());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 35;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 30:


                        do
                        {
                                v1 = (this.targetLocation).position;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 3f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 35;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 31:


                        do
                        {
                            ret = (this.Leave());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 36;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "BBqcSehsi0SL7khHmTYa1w") {
                _live = live;
                codeMatch = (codeKey == "jnrL8QdkXUeoDsEim0JNqA");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
