//%GenSrc:1:IerPsaHMEEWRCpCDeV8ysg
//%CodeKey:7hGm1v7t7EG9A3ljFCF0ZQ
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Staff.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    public partial class Staff : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            int n0c = -1;
            int n10c = -1;
            int n11c = -1;
            int n12c = -1;
            int n13c = -1;
            int n18c = -1;
            int n19c = -1;
            int n1c = -1;
            int n20c = -1;
            int n24c = -1;
            int n25c = -1;
            int n26c = -1;
            int n2c = -1;
            int n32c = -1;
            int n33c = -1;
            int n34c = -1;
            int n35c = -1;
            int n36c = -1;
            int n37c = -1;
            int n3c = -1;
            int n51c = -1;
            int n52c = -1;
            int n53c = -1;
            int n54c = -1;
            int n9c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n10_1r = NodeVal.Invalid;
            NodeVal n11_1r = NodeVal.Invalid;
            NodeVal n12_1r = NodeVal.Invalid;
            NodeVal n13_1r = NodeVal.Invalid;
            NodeVal n19_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n20_1r = NodeVal.Invalid;
            NodeVal n25_1r = NodeVal.Invalid;
            NodeVal n26_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n33_1r = NodeVal.Invalid;
            NodeVal n34_1r = NodeVal.Invalid;
            NodeVal n35_1r = NodeVal.Invalid;
            NodeVal n36_1r = NodeVal.Invalid;
            NodeVal n37_1r = NodeVal.Invalid;
            NodeVal n52_1r = NodeVal.Invalid;
            NodeVal n53_1r = NodeVal.Invalid;
            NodeVal n54_1r = NodeVal.Invalid;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 61:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 3) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 4;
                        node = 4;
                        n1_1r = NodeVal.Success;
                        break;
                    case 62:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 6) {
                            node = ++n1c;
                        } else {
                            n1c = 4;
                            node = 61;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 7;
                        node = 7;
                        n2_1r = NodeVal.Success;
                        break;
                    case 63:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 8) {
                            node = ++n2c;
                        } else {
                            n2c = 7;
                            node = 61;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 9;
                        node = 9;
                        n3_1r = NodeVal.Success;
                        break;
                    case 64:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 9) {
                            node = ++n3c;
                        } else {
                            n3c = 9;
                            node = 61;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        ret = (!this.spawned)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif
                        node = 62;
                        break;
                    case 5:


                        do
                        {
                            ret = (this.Spawn());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 62;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 6:


                        do
                        {
                            ret = (this.MoveTowards());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 62;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 7:

                        ret = ((transform.position - this.targetLocation).sqrMagnitude >= (1f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif
                        node = 63;
                        break;
                    case 8:


                        do
                        {
                            ret = (this.MoveTowards());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 63;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 9:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n9c = 10;
                        node = 10;
                        break;
                    case 70:

                        if(ret != NodeVal.Success) {
                            if (++n9c > 13) {
                                n9c = 10;
                                node = 64;
                            } else {
                                node = n9c;
                            }
                        } else {
                            n9c = 10;
                            node = 64;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 10:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(61, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n10c = 14;
                        node = 14;
                        n10_1r = NodeVal.Success;
                        break;
                    case 71:

                        n10_1r = (NodeVal)System.Math.Max((int)n10_1r, (int)ret);
                        if (ret == NodeVal.Success && n10c < 15) {
                            node = ++n10c;
                        } else {
                            n10c = 14;
                            node = 70;
                            ret = n10_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(61, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 11:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(44, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n11c = 16;
                        node = 16;
                        n11_1r = NodeVal.Success;
                        break;
                    case 72:

                        n11_1r = (NodeVal)System.Math.Max((int)n11_1r, (int)ret);
                        if (ret == NodeVal.Success && n11c < 18) {
                            node = ++n11c;
                        } else {
                            n11c = 16;
                            node = 70;
                            ret = n11_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(44, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 12:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n12c = 31;
                        node = 31;
                        n12_1r = NodeVal.Success;
                        break;
                    case 73:

                        n12_1r = (NodeVal)System.Math.Max((int)n12_1r, (int)ret);
                        if (ret == NodeVal.Success && n12c < 32) {
                            node = ++n12c;
                        } else {
                            n12c = 31;
                            node = 70;
                            ret = n12_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(0, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 13:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n13c = 49;
                        node = 49;
                        n13_1r = NodeVal.Success;
                        break;
                    case 74:

                        n13_1r = (NodeVal)System.Math.Max((int)n13_1r, (int)ret);
                        if (ret == NodeVal.Success && n13c < 51) {
                            node = ++n13c;
                        } else {
                            n13c = 49;
                            node = 70;
                            ret = n13_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 14:

                        ret = (this.movingToAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(59, _liveHandle, ret, false, false);
                        #endif
                        node = 71;
                        break;
                    case 15:


                        do
                        {
                            ret = (this.returnToAisle());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(60, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 71;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(60, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 16:

                        ret = (this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(46, _liveHandle, ret, false, false);
                        #endif
                        node = 72;
                        break;
                    case 17:

                        ret = (this.itemStocked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(50, _liveHandle, ret, false, false);
                        #endif
                        node = 72;
                        break;
                    case 18:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(45, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n18c = 19;
                        node = 19;
                        break;
                    case 79:

                        if(ret != NodeVal.Success) {
                            if (++n18c > 20) {
                                n18c = 19;
                                node = 72;
                            } else {
                                node = n18c;
                            }
                        } else {
                            n18c = 19;
                            node = 72;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(45, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 19:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(49, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n19c = 21;
                        node = 21;
                        n19_1r = NodeVal.Success;
                        break;
                    case 80:

                        n19_1r = (NodeVal)System.Math.Max((int)n19_1r, (int)ret);
                        if (ret == NodeVal.Success && n19c < 22) {
                            node = ++n19c;
                        } else {
                            n19c = 21;
                            node = 79;
                            ret = n19_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(49, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 20:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(48, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n20c = 23;
                        node = 23;
                        n20_1r = NodeVal.Success;
                        break;
                    case 81:

                        n20_1r = (NodeVal)System.Math.Max((int)n20_1r, (int)ret);
                        if (ret == NodeVal.Success && n20c < 24) {
                            node = ++n20c;
                        } else {
                            n20c = 23;
                            node = 79;
                            ret = n20_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(48, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 21:

                        ret = (!this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(53, _liveHandle, ret, false, false);
                        #endif
                        node = 80;
                        break;
                    case 22:


                        do
                        {
                            ret = (this.FindAisle());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(43, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 80;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(43, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 23:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(47, _liveHandle, ret, false, false);
                        #endif
                        node = 81;
                        break;
                    case 24:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(51, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n24c = 25;
                        node = 25;
                        break;
                    case 85:

                        if(ret != NodeVal.Success) {
                            if (++n24c > 26) {
                                n24c = 25;
                                node = 81;
                            } else {
                                node = n24c;
                            }
                        } else {
                            n24c = 25;
                            node = 81;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(51, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 25:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(52, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n25c = 27;
                        node = 27;
                        n25_1r = NodeVal.Success;
                        break;
                    case 86:

                        n25_1r = (NodeVal)System.Math.Max((int)n25_1r, (int)ret);
                        if (ret == NodeVal.Success && n25c < 28) {
                            node = ++n25c;
                        } else {
                            n25c = 27;
                            node = 85;
                            ret = n25_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(52, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 26:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(54, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n26c = 29;
                        node = 29;
                        n26_1r = NodeVal.Success;
                        break;
                    case 87:

                        n26_1r = (NodeVal)System.Math.Max((int)n26_1r, (int)ret);
                        if (ret == NodeVal.Success && n26c < 30) {
                            node = ++n26c;
                        } else {
                            n26c = 29;
                            node = 85;
                            ret = n26_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(54, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 27:

                        ret = (!this.firstCheck)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(55, _liveHandle, ret, false, false);
                        #endif
                        node = 86;
                        break;
                    case 28:


                        do
                        {
                            ret = (this.checkItemFirst());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(56, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 86;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(56, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 29:

                        ret = (this.firstCheck)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(57, _liveHandle, ret, false, false);
                        #endif
                        node = 87;
                        break;
                    case 30:


                        do
                        {
                            ret = (this.checkItemSecond());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(58, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 87;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(58, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 31:

                        ret = (!this.itemStocked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, false, false);
                        #endif
                        node = 73;
                        break;
                    case 32:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n32c = 33;
                        node = 33;
                        break;
                    case 93:

                        if(ret != NodeVal.Success) {
                            if (++n32c > 37) {
                                n32c = 33;
                                node = 73;
                            } else {
                                node = n32c;
                            }
                        } else {
                            n32c = 33;
                            node = 73;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 33:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n33c = 38;
                        node = 38;
                        n33_1r = NodeVal.Success;
                        break;
                    case 94:

                        n33_1r = (NodeVal)System.Math.Max((int)n33_1r, (int)ret);
                        if (ret == NodeVal.Success && n33c < 39) {
                            node = ++n33c;
                        } else {
                            n33c = 38;
                            node = 93;
                            ret = n33_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 34:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n34c = 40;
                        node = 40;
                        n34_1r = NodeVal.Success;
                        break;
                    case 95:

                        n34_1r = (NodeVal)System.Math.Max((int)n34_1r, (int)ret);
                        if (ret == NodeVal.Success && n34c < 42) {
                            node = ++n34c;
                        } else {
                            n34c = 40;
                            node = 93;
                            ret = n34_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 35:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n35c = 43;
                        node = 43;
                        n35_1r = NodeVal.Success;
                        break;
                    case 96:

                        n35_1r = (NodeVal)System.Math.Max((int)n35_1r, (int)ret);
                        if (ret == NodeVal.Success && n35c < 44) {
                            node = ++n35c;
                        } else {
                            n35c = 43;
                            node = 93;
                            ret = n35_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 36:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n36c = 45;
                        node = 45;
                        n36_1r = NodeVal.Success;
                        break;
                    case 97:

                        n36_1r = (NodeVal)System.Math.Max((int)n36_1r, (int)ret);
                        if (ret == NodeVal.Success && n36c < 46) {
                            node = ++n36c;
                        } else {
                            n36c = 45;
                            node = 93;
                            ret = n36_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 37:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n37c = 47;
                        node = 47;
                        n37_1r = NodeVal.Success;
                        break;
                    case 98:

                        n37_1r = (NodeVal)System.Math.Max((int)n37_1r, (int)ret);
                        if (ret == NodeVal.Success && n37c < 48) {
                            node = ++n37c;
                        } else {
                            n37c = 47;
                            node = 93;
                            ret = n37_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 38:

                        ret = (this.movingToStockRoom)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, ret, false, false);
                        #endif
                        node = 94;
                        break;
                    case 39:


                        do
                        {
                            ret = (this.MoveToStockRoom());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 94;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 40:

                        ret = (!this.atStock)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, ret, false, false);
                        #endif
                        node = 95;
                        break;
                    case 41:

                        ret = (this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, ret, false, false);
                        #endif
                        node = 95;
                        break;
                    case 42:


                        do
                        {
                            ret = (this.MoveToStockLocation());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 95;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 43:

                        ret = (this.atStock)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(19, _liveHandle, ret, false, false);
                        #endif
                        node = 96;
                        break;
                    case 44:


                        do
                        {
                            ret = (this.getItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 96;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 45:

                        ret = (this.movingToShelf)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, ret, false, false);
                        #endif
                        node = 97;
                        break;
                    case 46:


                        do
                        {
                            ret = (this.moveBackToShelf());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 97;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 47:

                        ret = (!this.movingToShelf)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, ret, false, false);
                        #endif
                        node = 98;
                        break;
                    case 48:


                        do
                        {
                            ret = (this.stockItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 98;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 49:

                        ret = (!this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, ret, false, false);
                        #endif
                        node = 74;
                        break;
                    case 50:

                        ret = (this.itemStocked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, ret, false, false);
                        #endif
                        node = 74;
                        break;
                    case 51:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(42, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n51c = 52;
                        node = 52;
                        break;
                    case 112:

                        if(ret != NodeVal.Success) {
                            if (++n51c > 54) {
                                n51c = 52;
                                node = 74;
                            } else {
                                node = n51c;
                            }
                        } else {
                            n51c = 52;
                            node = 74;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(42, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 52:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n52c = 55;
                        node = 55;
                        n52_1r = NodeVal.Success;
                        break;
                    case 113:

                        n52_1r = (NodeVal)System.Math.Max((int)n52_1r, (int)ret);
                        if (ret == NodeVal.Success && n52c < 56) {
                            node = ++n52c;
                        } else {
                            n52c = 55;
                            node = 112;
                            ret = n52_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 53:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n53c = 57;
                        node = 57;
                        n53_1r = NodeVal.Success;
                        break;
                    case 114:

                        n53_1r = (NodeVal)System.Math.Max((int)n53_1r, (int)ret);
                        if (ret == NodeVal.Success && n53c < 58) {
                            node = ++n53c;
                        } else {
                            n53c = 57;
                            node = 112;
                            ret = n53_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 54:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(41, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n54c = 59;
                        node = 59;
                        n54_1r = NodeVal.Success;
                        break;
                    case 115:

                        n54_1r = (NodeVal)System.Math.Max((int)n54_1r, (int)ret);
                        if (ret == NodeVal.Success && n54c < 60) {
                            node = ++n54c;
                        } else {
                            n54c = 59;
                            node = 112;
                            ret = n54_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(41, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 55:

                        ret = (this.movingToStockRoom)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, ret, false, false);
                        #endif
                        node = 113;
                        break;
                    case 56:


                        do
                        {
                            ret = (this.MoveToStockRoom());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 113;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 57:

                        ret = (!this.atStock)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, ret, false, false);
                        #endif
                        node = 114;
                        break;
                    case 58:


                        do
                        {
                            ret = (this.MoveToStockLocation());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 114;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 59:

                        ret = (this.atStock)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(39, _liveHandle, ret, false, false);
                        #endif
                        node = 115;
                        break;
                    case 60:


                        do
                        {
                            ret = (this.returnStock());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 115;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "IerPsaHMEEWRCpCDeV8ysg") {
                _live = live;
                codeMatch = (codeKey == "7hGm1v7t7EG9A3ljFCF0ZQ");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
