//%GenSrc:1:IerPsaHMEEWRCpCDeV8ysg
//%CodeKey:iq4yMX6ND0GPMkKylLHUfA
/*
 * This code was generated by InstinctAI
 *
 *         DO NOT MODIFY BY HAND
 *     THIS FILE WILL BE REGENERATED
 *
 *      DO NOT REMOVE/EDIT COMMENTS
 *
 * If you do need to modify this file, note that it is a partial class.
 * See https://msdn.microsoft.com/en-us/library/wa80x488.aspx
 * You can edit the file Staff.cs
 */

namespace instinctai.usr.behaviours
{
    using System.Collections;
    using UnityEngine;
    using com.kupio.instinctai;
#if UNITY_EDITOR
    using UnityEditor;
    using com.kupio.instinctai.live;
#endif

    public partial class Staff : MonoBehaviour
#if UNITY_EDITOR
        , LiveTree
#endif
    {
        private IEnumerator _state = null;
        private int _jmp;
        private bool valid = true;

#if UNITY_EDITOR
    private LiveUpdate _live;
    private int _liveHandle;
#endif

        void Update()
        {
            if (valid) {
                if (_state == null || _state.MoveNext() == false) {
                    _state = StateGen();
                    _state.MoveNext();
                }
            }
        }
        private IEnumerator StateGen()
        {
            int node = 0;
            NodeVal ret = NodeVal.Error;
            _jmp = -1;
            int n0c = -1;
            int n14c = -1;
            int n15c = -1;
            int n16c = -1;
            int n1c = -1;
            int n22c = -1;
            int n23c = -1;
            int n24c = -1;
            int n25c = -1;
            int n26c = -1;
            int n2c = -1;
            int n3c = -1;
            int n6c = -1;
            int n7c = -1;
            int n8c = -1;
            NodeVal n1_1r = NodeVal.Invalid;
            NodeVal n15_1r = NodeVal.Invalid;
            NodeVal n16_1r = NodeVal.Invalid;
            NodeVal n2_1r = NodeVal.Invalid;
            NodeVal n23_1r = NodeVal.Invalid;
            NodeVal n24_1r = NodeVal.Invalid;
            NodeVal n25_1r = NodeVal.Invalid;
            NodeVal n26_1r = NodeVal.Invalid;
            NodeVal n3_1r = NodeVal.Invalid;
            NodeVal n7_1r = NodeVal.Invalid;
            NodeVal n8_1r = NodeVal.Invalid;
            Vector3 v1 = Vector3.zero;

            if (!valid) {
                throw new BehaviourTreeException("Behaviour tree will not run. The GameObject has missing required components.");
            }
            do {
                switch (node) {
                    case 0:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, NodeVal.Running, false, true);
                        #endif
                        n0c = 1;
                        node = 1;
                        break;
                    case 40:

                        if (_jmp >= 0) {
                            node = _jmp;
                            _jmp = -1;
                            continue;
                        }
                        if(ret != NodeVal.Success) {
                            if (++n0c > 3) {
                                n0c = 1;
                                node = 0;
                                yield return null;
                            } else {
                                node = n0c;
                            }
                        } else {
                            n0c = 1;
                            node = 0;
                            yield return null;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(7, _liveHandle, ret, true, false);
                        #endif
                        break;
                    case 1:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n1c = 4;
                        node = 4;
                        n1_1r = NodeVal.Success;
                        break;
                    case 41:

                        n1_1r = (NodeVal)System.Math.Max((int)n1_1r, (int)ret);
                        if (ret == NodeVal.Success && n1c < 6) {
                            node = ++n1c;
                        } else {
                            n1c = 4;
                            node = 40;
                            ret = n1_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(5, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 2:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n2c = 21;
                        node = 21;
                        n2_1r = NodeVal.Success;
                        break;
                    case 42:

                        n2_1r = (NodeVal)System.Math.Max((int)n2_1r, (int)ret);
                        if (ret == NodeVal.Success && n2c < 22) {
                            node = ++n2c;
                        } else {
                            n2c = 21;
                            node = 40;
                            ret = n2_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(8, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 3:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n3c = 37;
                        node = 37;
                        n3_1r = NodeVal.Success;
                        break;
                    case 43:

                        n3_1r = (NodeVal)System.Math.Max((int)n3_1r, (int)ret);
                        if (ret == NodeVal.Success && n3c < 39) {
                            node = ++n3c;
                        } else {
                            n3c = 37;
                            node = 40;
                            ret = n3_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(6, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 4:

                        ret = (this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(3, _liveHandle, ret, false, false);
                        #endif
                        node = 41;
                        break;
                    case 5:

                        ret = (this.itemStocked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(4, _liveHandle, ret, false, false);
                        #endif
                        node = 41;
                        break;
                    case 6:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n6c = 7;
                        node = 7;
                        break;
                    case 46:

                        if(ret != NodeVal.Success) {
                            if (++n6c > 8) {
                                n6c = 7;
                                node = 41;
                            } else {
                                node = n6c;
                            }
                        } else {
                            n6c = 7;
                            node = 41;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(2, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 7:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n7c = 9;
                        node = 9;
                        n7_1r = NodeVal.Success;
                        break;
                    case 47:

                        n7_1r = (NodeVal)System.Math.Max((int)n7_1r, (int)ret);
                        if (ret == NodeVal.Success && n7c < 11) {
                            node = ++n7c;
                        } else {
                            n7c = 9;
                            node = 46;
                            ret = n7_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(1, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 8:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n8c = 12;
                        node = 12;
                        n8_1r = NodeVal.Success;
                        break;
                    case 48:

                        n8_1r = (NodeVal)System.Math.Max((int)n8_1r, (int)ret);
                        if (ret == NodeVal.Success && n8c < 14) {
                            node = ++n8c;
                        } else {
                            n8c = 12;
                            node = 46;
                            ret = n8_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(12, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 9:

                        ret = (!this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(9, _liveHandle, ret, false, false);
                        #endif
                        node = 47;
                        break;
                    case 10:


                        do
                        {
                            ret = (this.FindAisle());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 47;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(10, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 11:


                        do
                        {
                                v1 = this.targetLocation;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 5f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 47;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(11, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 12:

                        ret = ((transform.position - this.targetLocation).sqrMagnitude <= (0.25f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(13, _liveHandle, ret, false, false);
                        #endif
                        node = 48;
                        break;
                    case 13:

                        ret = (this.foundAisle)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(14, _liveHandle, ret, false, false);
                        #endif
                        node = 48;
                        break;
                    case 14:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n14c = 15;
                        node = 15;
                        break;
                    case 54:

                        if(ret != NodeVal.Success) {
                            if (++n14c > 16) {
                                n14c = 15;
                                node = 48;
                            } else {
                                node = n14c;
                            }
                        } else {
                            n14c = 15;
                            node = 48;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(15, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 15:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n15c = 17;
                        node = 17;
                        n15_1r = NodeVal.Success;
                        break;
                    case 55:

                        n15_1r = (NodeVal)System.Math.Max((int)n15_1r, (int)ret);
                        if (ret == NodeVal.Success && n15c < 18) {
                            node = ++n15c;
                        } else {
                            n15c = 17;
                            node = 54;
                            ret = n15_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(16, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 16:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n16c = 19;
                        node = 19;
                        n16_1r = NodeVal.Success;
                        break;
                    case 56:

                        n16_1r = (NodeVal)System.Math.Max((int)n16_1r, (int)ret);
                        if (ret == NodeVal.Success && n16c < 20) {
                            node = ++n16c;
                        } else {
                            n16c = 19;
                            node = 54;
                            ret = n16_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(17, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 17:

                        ret = (!this.firstCheck)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(19, _liveHandle, ret, false, false);
                        #endif
                        node = 55;
                        break;
                    case 18:


                        do
                        {
                            ret = (this.checkItemFirst());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 55;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(18, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 19:

                        ret = (this.firstCheck)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(20, _liveHandle, ret, false, false);
                        #endif
                        node = 56;
                        break;
                    case 20:


                        do
                        {
                            ret = (this.checkItemSecond());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 56;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(21, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 21:

                        ret = (!this.itemStocked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(26, _liveHandle, ret, false, false);
                        #endif
                        node = 42;
                        break;
                    case 22:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n22c = 23;
                        node = 23;
                        break;
                    case 62:

                        if(ret != NodeVal.Success) {
                            if (++n22c > 26) {
                                n22c = 23;
                                node = 42;
                            } else {
                                node = n22c;
                            }
                        } else {
                            n22c = 23;
                            node = 42;
                        }

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(27, _liveHandle, ret, false, false);
                        #endif
                        break;
                    case 23:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n23c = 27;
                        node = 27;
                        n23_1r = NodeVal.Success;
                        break;
                    case 63:

                        n23_1r = (NodeVal)System.Math.Max((int)n23_1r, (int)ret);
                        if (ret == NodeVal.Success && n23c < 29) {
                            node = ++n23c;
                        } else {
                            n23c = 27;
                            node = 62;
                            ret = n23_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(22, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 24:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n24c = 30;
                        node = 30;
                        n24_1r = NodeVal.Success;
                        break;
                    case 64:

                        n24_1r = (NodeVal)System.Math.Max((int)n24_1r, (int)ret);
                        if (ret == NodeVal.Success && n24c < 31) {
                            node = ++n24c;
                        } else {
                            n24c = 30;
                            node = 62;
                            ret = n24_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(28, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 25:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n25c = 32;
                        node = 32;
                        n25_1r = NodeVal.Success;
                        break;
                    case 65:

                        n25_1r = (NodeVal)System.Math.Max((int)n25_1r, (int)ret);
                        if (ret == NodeVal.Success && n25c < 34) {
                            node = ++n25c;
                        } else {
                            n25c = 32;
                            node = 62;
                            ret = n25_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(29, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 26:

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, NodeVal.Running, false, false);
                        #endif
                        n26c = 35;
                        node = 35;
                        n26_1r = NodeVal.Success;
                        break;
                    case 66:

                        n26_1r = (NodeVal)System.Math.Max((int)n26_1r, (int)ret);
                        if (ret == NodeVal.Success && n26c < 36) {
                            node = ++n26c;
                        } else {
                            n26c = 35;
                            node = 62;
                            ret = n26_1r;

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(30, _liveHandle, ret, false, false);
                        #endif

                        }
                        break;
                    case 27:

                        ret = ((transform.position - this.targetLocation).sqrMagnitude >= (9f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(32, _liveHandle, ret, false, false);
                        #endif
                        node = 63;
                        break;
                    case 28:

                        ret = (this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(31, _liveHandle, ret, false, false);
                        #endif
                        node = 63;
                        break;
                    case 29:


                        do
                        {
                                v1 = this.targetLocation;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 5f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 63;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(33, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 30:

                        ret = (this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(34, _liveHandle, ret, false, false);
                        #endif
                        node = 64;
                        break;
                    case 31:


                        do
                        {
                            ret = (this.getItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 64;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(35, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 32:

                        ret = (!this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(36, _liveHandle, ret, false, false);
                        #endif
                        node = 65;
                        break;
                    case 33:

                        ret = ((transform.position - this.targetLocation).sqrMagnitude >= (9f))? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(37, _liveHandle, ret, false, false);
                        #endif
                        node = 65;
                        break;
                    case 34:


                        do
                        {
                                v1 = this.targetLocation;
                            transform.position = Vector3.MoveTowards(transform.position, v1, 5f * Time.deltaTime);
                            ret = (transform.position == v1)? NodeVal.Success : NodeVal.Running;
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 65;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(38, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 35:

                        ret = (!this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(39, _liveHandle, ret, false, false);
                        #endif
                        node = 66;
                        break;
                    case 36:


                        do
                        {
                            ret = (this.stockItem());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 66;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(40, _liveHandle, ret, false, false);
                        #endif

                        break;
                    case 37:

                        ret = (!this.inventoryEmpty)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(23, _liveHandle, ret, false, false);
                        #endif
                        node = 43;
                        break;
                    case 38:

                        ret = (this.itemStocked)? NodeVal.Success : NodeVal.Fail;
                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(24, _liveHandle, ret, false, false);
                        #endif
                        node = 43;
                        break;
                    case 39:


                        do
                        {
                            ret = (this.returnStock());
                            if (ret == NodeVal.Running) {

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, NodeVal.Running, true, false);
                        #endif
                                yield return null;
                            } else {
                                node = 43;
                                break;
                            }
                        } while (true);

                        #if UNITY_EDITOR
                            if (_live != null) _live = _live.SetLiveValue(25, _liveHandle, ret, false, false);
                        #endif

                        break;
                }
            } while (node >= 0);
            yield return null;
        }
        public void ResetTree()
        {
            if (_jmp != 0)
            {
                _jmp = 0;
            }
        }
#if UNITY_EDITOR
        public bool SetLive(LiveUpdate live, string treeKey, string codeKey, int liveHandle, out bool codeMatch) {
            if (treeKey == "IerPsaHMEEWRCpCDeV8ysg") {
                _live = live;
                codeMatch = (codeKey == "iq4yMX6ND0GPMkKylLHUfA");
                if (codeMatch) {
                    _liveHandle = liveHandle;
                }
                return true;
            }
            codeMatch = false;
            return false;
        }
#endif

    }
}
